### ISSUE TITLE
Not available in the latest XS

### ISSUE THREAD

**Issue by naveensrinivasan** [mrward/monodevelop-paket-addin#1]
I tried looking for it in the Alpha Channel and I still don't see it in the Xamarin Addins.

**Comment by davidschwegler** [comment]
@mrward Hey Matt, is this something that can be fixed?

**Comment by mrward** [comment]
Yeah I have not updated it for Xamarin Studio 6 yet. I put off porting while the Xamarin Studio 6 API was not stable which it should be now. I just have not gotten around to updating it along with some of my other addins.

**Comment by davidschwegler** [comment]
Understandable. Definitely hoping you can get this in your task queue soon, though! Our teams require the latest Xamarin Studio.

**Comment by mrward** [comment]
Version 0.1 of the Paket addin should now be available from the Xamarin Studio add-in repository (Beta channel) for Xamarin Studio 6.
