### ISSUE TITLE
[Monodevelop 5.10] Install error

### ISSUE THREAD

**Issue by mfdeveloper** [mrward/monodevelop-paket-addin#10]
Hello there!! 

I've got an error when try install this addin on `Monodevelop 5.10`.  Using **`Monodevelop 5.9.6`**, was installed succesfull. 

Please, see the screen below:

![monodevelop 5 10 paket error](https://user-images.githubusercontent.com/431606/30701524-d4bcc1be-9ec0-11e7-8fd9-4a15bc2776fc.png).

**Comment by mrward** [comment]
The error message does not seem to be related the Paket addin. It is from the ASP.NET addin. You could try disabling the ASP.NET addin, installing the Paket addin, if it failed to install, then re-enable the ASP.NET addin.

**Comment by mfdeveloper** [comment]
@mrward Sure!! I don't know why this ASP.NET addin shows this warning. I thought this error is because the **Paket** addin uses this like their dependency.

So, after that disabled the ASP.NET addin, the **Paket** addin was installed succesfull.

Many thanks for you help!!
