### ISSUE TITLE
Update paket to a more recent version

### ISSUE THREAD

**Issue by ylatuya** [mrward/monodevelop-paket-addin#11]
Hi, 
We are using this plugin in Visual Studio for mac but the version shipped with the plugin is too old and it doesn't support things like "restriction: >= net45".
We tried to simply upgrade the paket.exe binary in the plugin but it does not seems to work.
Is it possible to upgrade paket to a more recent version?

**Comment by mrward** [comment]
Yeah sure.

What I was thinking of doing was not using a particular Paket version but instead just looking for paket.exe somewhere in the solution, or keep going up a directly until it is found, and then just running that directly using its command line parameters. Currently the addin directly references paket and uses its assembly directly.

**Comment by ylatuya** [comment]
It could be a good solution if paket provides an application interface that's backwards compatible. What we found out is that with the new version of paket the plugin just shows empty strings and commands don't work, maybe we did something wrong. If there is a way to provide you debug logs let me know, or maybe you can't reproduce it and it just works, in that case we will just wait for the update.
By the way, thanks for this great plugin :D

**Comment by mrward** [comment]
There is a new build of the [Paket addin (version 0.4)](https://github.com/mrward/monodevelop-addins/blob/gh-pages/7.0/MonoDevelop.Paket_0.4.mpack) that uses a more recent Paket version (5.120.1). Also fixed some other problems, such as code completion not working in paket.dependencies. You should be able to download this .mpack and install it from the Extensions Manager dialog using the Install from file button.

Currently the main addin server for VS Mac seems to have problems so it is unlikely this addin will be published there any time soon.

**Comment by mrward** [comment]
It might be easier to add the custom addin server url where I host these addins rather than download the .mpack and install it. There's a different url based on what VS Mac version you are using.

https://github.com/mrward/monodevelop-addins
