### ISSUE TITLE
Update Paket

### ISSUE THREAD

**Issue by sideeffffect** [mrward/monodevelop-paket-addin#3]
Could you please update to the newest version of `Paket`, please?
The newest version is `3.x` as of today, while this extension works with `1.x`.
That means that it e. g. can't work with ["Dependency Groups"](https://fsprojects.github.io/Paket/groups.html) in `paket.dependencies`/`paket.references`.

**Comment by mrward** [comment]
Updated to Paket Paket 3.23.2.

There is no explicit support in the addin for dependency groups currently.
