### ISSUE TITLE
VS for Mac?

### ISSUE THREAD

**Issue by alexreg** [mrward/monodevelop-paket-addin#9]
Will this project be moving forward with MonoDevelop and Xamarin Studio now being superseded by Visual Studio for Mac?

**Comment by mrward** [comment]
Visual Studio Mac corresponds to MonoDevelop 7.0. Xamarin Studio's last release was 6.3 which corresponds to MonoDevelop 6.3. Unless there is interest for shipping updates for MonoDevelop 6.0 I was planning on only updating it for Visual Studio for Mac and therefore MonoDevelop 7.0.

**Comment by alexreg** [comment]
Yeah, that sounds like a fair plan.

Maybe renaming the project accordingly would help more people to find it? :)

**Comment by mrward** [comment]
No plans to rename the project since it supports MonoDevelop.
